### ISSUE TITLE
Download ratings only data and build recommendations using completed ratings

### ISSUE THREAD

**Issue by dingchaozhang-tc** [shhudspeth/BookRecommendationSystem#1]
The [book ratings data ](http://snap.stanford.edu/data/amazon/productGraph/categoryFiles/ratings_Books.csv) is small-ish(900~ mb) to fit into memory(tested), as it only contains user,item,rating,timestamp four columns only.

**Comment by shhudspeth** [comment]
I saved a csv file to use with only these columns. it should load on next push.
