### ISSUE TITLE
Create metrics to perform evaluation of recommendation results

### ISSUE THREAD

**Issue by dingchaozhang-tc** [shhudspeth/BookRecommendationSystem#2]
Design and create [precision and recall at K](https://medium.com/@m_n_malaeb/recall-and-precision-at-k-for-recommender-systems-618483226c54)  metrics to evaluate and compare different recommender system's results on test dataset.

**Comment by dingchaozhang-tc** [comment]
One way to evaluate is using the following metrics: 
Precision@k = (# of recommended items @k that are relevant) / (# of recommended items @k)
Recall@k = (# of recommended items @k that are relevant) / (total # of relevant items)
Steps:
- Pick a threshold: assume a book is interested by a user if the rating is above a certain threshold say 3,  or visualize by plotting the histogram of ratings and then pick a threshold that roughly is 50 percentile.  
-  Turn the ratings into binary for users: relevant and un-relevant using the threshold picked.
-  Compute precision-k and recall-k.

**Comment by dingchaozhang-tc** [comment]
Recommended items(predicted items) are the recommendation returned from the model/ algorithms, and the relevant items(actual items that user are interested/ giving high rating).

**Comment by shhudspeth** [comment]
See Recommender with Surprise Notebook, I believe i touched on all these points. I did two precision/recall methods one with an average threshold of relevancy and one with a user-averaged threshold based on the number of reviews they give out. I plot their respective roc-curves.
