### ISSUE TITLE
Split the utility matrix into training and testing

### ISSUE THREAD

**Issue by dingchaozhang-tc** [shhudspeth/BookRecommendationSystem#3]

**Comment by dingchaozhang-tc** [comment]
A possible approach to generate training and testing is:
- Identify users who have a considerate amount of ratings, e.g. more than 5 ratings.
- Randomly replace some(e.g. 20%) of the ratings for those users with 0 in the original utility matrix, which becomes the training data, and the 0-marked-up ratings for those users is testing data, the original ratings is the ground truth.
-  Run the recommendations on the testing dataset, record the recommendation ratings and evaluate against with the original ratings using RMSE or Precision/Recall-K methods.

**Comment by dingchaozhang-tc** [comment]
How to generate quantitative rating for a book/ user pair :
The averaged ratings of the five closest books

**Comment by shhudspeth** [comment]
Completed. The recommender returned RMSE for Sparse Utility Matrix was 1.11.
